= Defining New Input Types
:toc: left
include::../attributes.adoc[]

Contributions are welcome — bug fixes, interface improvements, and new features.
To report an issue or propose a change, open a ticket on link:https://github.com/gesinn-it/mediawiki-extensions-PageForms/issues[GitHub Issues].

The source code is hosted at link:https://github.com/gesinn-it/mediawiki-extensions-PageForms[github.com/gesinn-it/mediawiki-extensions-PageForms].

== Defining New Inputs

To create a new input type, you need to define a class for that input, and have it inherit (using the `extends` keyword) from the class `PFFormInput`, or one of its child classes.

There are a number of methods that this class can or should define; the following are the crucial ones:

* `getName()` — sets the name of the input within the form definition.
* `getParameters()` — defines which parameters can be passed in to this input (used by the form printer when rendering field options).
* `getHtmlText()` — defines the HTML to display this input.
* `getResourceModuleNames()` — sets the name(s) of the ResourceLoader modules used by this input; if the input contains any JavaScript or CSS, they should be packaged into one or more modules, which are then specified here.

Other methods that can be overridden include the following:

* `getHandledPropertyTypes()`
* `getDefaultParameters()`
* `canHandleLists()`

It's useful to look at the existing form input classes to see how all these functions are called.

One note on getting other parameters: let's say that your input is named "myinput", and is called in the form definition in the following way:

----
{{{field|Some Field|input type=myinput|color=orange|height=200}}}
----

Within your class's `getHtmlText()` method, `$this->mOtherArgs` will contain the `color=orange` and `height=200` key-value pairs, which the function can then use however it wants.

Finally, once your new input is defined, it needs to be registered.
You do that by using the `'PageForms::FormPrinterSetup'` hook.
You need to register with that hook a function that looks like the following:

[source,php]
----
public static function onFormPrinterSetup( &$pfFormPrinter ) {
    $pfFormPrinter->registerInputType( 'MyInputClass' );
}
----

== Testing

You can find information on testing the code at the xref:index.adoc[Developer Guide index].
