= Installation
:toc: left
include::../attributes.adoc[]

== Download

Clone the repository from GitHub into your MediaWiki `extensions` directory:

[source,bash]
----
git clone https://github.com/gesinn-it/mediawiki-extensions-PageForms.git PageForms
----

Releases and version history are available at link:https://github.com/gesinn-it/mediawiki-extensions-PageForms/releases[github.com/gesinn-it/mediawiki-extensions-PageForms].

== Installation

Once the code is in your `extensions/PageForms` directory, add the following line to `LocalSettings.php`:

[source,php]
----
wfLoadExtension( 'PageForms' );
----

=== User rights

Page Forms defines three user rights:

`editrestrictedfields`::
Permission to edit fields marked as `restricted` in a form definition.
By default granted to members of the `sysop` group.

`multipageedit`::
Permission to use `Special:MultiPageEdit`.
By default granted to members of the `user` group.

`viewedittab`::
Permission to see the "Edit with form" tab on pages that have a form assigned.
By default granted to everyone (`*`).

These defaults can be overridden in `LocalSettings.php` after the extension is loaded.
For example, to restrict the "Edit with form" tab to administrators:

[source,php]
----
$wgGroupPermissions['*']['viewedittab'] = false;
$wgGroupPermissions['sysop']['viewedittab'] = true;
----

== Composer

Page Forms can also be installed via link:https://www.mediawiki.org/wiki/Composer[Composer].
Add the following to `composer.local.json`:

[source,json]
----
{
  "require": {
    "mediawiki/page-forms": "^2.0"
  }
}
----

The package is listed on Packagist: link:https://packagist.org/packages/mediawiki/page-forms[mediawiki/page-forms].

== Upgrading

To update an existing Git installation to the latest version:

[source,bash]
----
git pull
----
