= Special Pages
:toc: left
include::../attributes.adoc[]

{project_name} defines various special pages, used for a variety of purposes.

== Directory Pages

Two special pages provide lists of the data-structure pages within the wiki:

* *Special:Forms* — lists all form pages on the site.
* *Special:Templates* — lists all templates on the site.

== Operational Pages

Five special pages are used in the standard running of {project_name}:

* *Special:FormEdit* — lets a user either create or edit a page using a user-created form.
* *Special:FormStart* — used to route a user to either `FormEdit` or the relevant page's "edit with form" tab. This page should not be accessed directly by users.
* *Special:RunQuery* — lets a user run a query using a form; see xref:query-forms.adoc[Creating query forms] for more information.
* *Special:UploadWindow* — lets a user upload a file; very similar to the standard `Special:Upload` page, but without the skin. This page is called from within a form and should not be accessed directly by users.
* *Special:MultiPageEdit* — lets a user select a template and edit all the pages that contain it using a spreadsheet-like interface. The user can also create new pages and rename existing ones. Other features include pagination and a selector for the number of rows to display at once. It currently supports text, text area, checkbox, date, combobox, and tokens input types.
