name: Build Copilot Instructions

on:
  push:
    paths:
      - docs-master/**
      - .github/copilot-instructions-source.adoc
    branches:
      - '**'
  workflow_dispatch:

jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      # apt pandoc does not support asciidoc input
      - name: Install pandoc
        run: |
          PANDOC_VERSION=3.2
          wget -q https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb
          sudo dpkg -i pandoc-${PANDOC_VERSION}-1-amd64.deb

      - name: Reduce instructions source
        run: |
          asciidoctor-reducer \
            -o .github/copilot-instructions.adoc \
            .github/copilot-instructions-source.adoc

      - name: Convert to Markdown
        run: |
          pandoc \
            -f asciidoc \
            -t gfm \
            .github/copilot-instructions.adoc \
            -o .github/copilot-instructions.md

      - name: Add autogenerated header
        run: |
          printf "<!-- THIS FILE IS AUTO-GENERATED. Edit .github/copilot-instructions-source.adoc instead. -->\n\n" | \
          cat - .github/copilot-instructions.md > tmp
          mv tmp .github/copilot-instructions.md

      - name: Remove intermediate file
        run: rm .github/copilot-instructions.adoc

      - name: Commit generated instructions
        uses: EndBug/add-and-commit@v8
        with:
          add: '.github/copilot-instructions.md'
          message: "docs(copilot): update generated instructions [skip ci]"